CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       CHARACTER varying(128) NOT NULL,
    text        TEXT                   NOT NULL,
    likes_count INT DEFAULT 0
);

CREATE TABLE comment
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    TEXT                        NOT NULL,
    post_id BIGINT REFERENCES Post (id) NOT NULL
);

CREATE TABLE post_image
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  BIGINT NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    filename TEXT   NOT NULL,
    UNIQUE (post_id)
);

CREATE TABLE tag
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    UNIQUE (title)
);

CREATE TABLE post_tag
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id  BIGINT REFERENCES Tag (id) ON DELETE CASCADE  NOT NULL,
    post_id BIGINT REFERENCES Post (id) ON DELETE CASCADE NOT NULL

);

ALTER TABLE post
    ADD COLUMN created_at timestamp;

ALTER TABLE comment
    ADD COLUMN created_at timestamp;


alter table post
    alter column created_at set default now();

alter table comment
    alter column created_at set default now();


SELECT
    p.id,
    p.title,
    p.text,
    p.likes_count,
    COUNT(DISTINCT c.id)            AS comments_count,
    ARRAY_AGG(DISTINCT t.title)
    FILTER (WHERE t.title IS NOT NULL) AS tags
FROM post p
         LEFT JOIN comment c
                   ON c.post_id = p.id
         LEFT JOIN post_tag pt
                   ON pt.post_id = p.id
         LEFT JOIN tag t
                   ON t.id = pt.tag_id
WHERE p.title LIKE '%12%'
GROUP BY
    p.id,
    p.title,
    p.text,
    p.likes_count,
    p.created_at
order by p.created_at
offset 0
limit 20''


ALTER TABLE post_tag
    ADD CONSTRAINT post_tag_unique UNIQUE (post_id, tag_id);

truncate post_tag;

