DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS tag CASCADE;
DROP TABLE IF EXISTS post_image CASCADE;
DROP TABLE IF EXISTS post_tag CASCADE;


CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       CHARACTER varying(128) NOT NULL,
    text        TEXT                   NOT NULL,
    likes_count INT DEFAULT 0
);

CREATE TABLE comment
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text    TEXT                                          NOT NULL,
    post_id BIGINT REFERENCES Post (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE post_image
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id  BIGINT NOT NULL REFERENCES post (id) ON DELETE CASCADE,
    filename TEXT   NOT NULL,
    UNIQUE (post_id)
);

CREATE TABLE tag
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    UNIQUE (title)
);

CREATE TABLE post_tag
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id  BIGINT REFERENCES Tag (id) ON DELETE CASCADE  NOT NULL,
    post_id BIGINT REFERENCES Post (id) ON DELETE CASCADE NOT NULL
);

ALTER TABLE post
    ADD COLUMN created_at timestamp;

ALTER TABLE comment
    ADD COLUMN created_at timestamp;


alter table post
    alter column created_at set default now();

alter table comment
    alter column created_at set default now();

ALTER TABLE post_tag
    ADD CONSTRAINT post_tag_unique UNIQUE (post_id, tag_id);